services:
  ## Slack
  TurboLabIt\Messengers\SlackMessenger:
    autowire: true
    public: true
    arguments:
      $arrConfig:
        Slack:
          enabled: '%env(APP_SLACK_ENABLED)%'
          token: '%env(APP_SLACK_TOKEN)%'
          channelId: '%env(APP_SLACK_CHANNEL_ID)%'
          errorsChannelId: '%env(APP_SLACK_ERRORS_CHANNEL_ID)%'

  ## Telegram
  TurboLabIt\Messengers\TelegramMessenger:
    autowire: true
    public: true
    arguments:
      $arrConfig:
        Telegram:
          enabled: '%env(APP_TELEGRAM_ENABLED)%'
          token: '%env(APP_TELEGRAM_TOKEN)%'
          channelId: '%env(APP_TELEGRAM_CHANNEL_ID)%'

  ## Facebook
  TurboLabIt\Messengers\FacebookMessenger:
    autowire: true
    public: true
    arguments:
        $arrConfig:
            Facebook:
                enabled: '%env(APP_FACEBOOK_ENABLED)%'
                page:
                  id: '%env(APP_FACEBOOK_PAGE_ID)%'
                  token: '%env(APP_FACEBOOK_PAGE_TOKEN)%'

  ## Twitter
  TurboLabIt\Messengers\TwitterMessenger:
    autowire: true
    public: true
    arguments:
      $arrConfig:
        Twitter:
          enabled: '%env(APP_TWITTER_ENABLED)%'
          id: '%env(APP_TWITTER_ID)%'
          apiKey: '%env(APP_TWITTER_API_KEY)%'
          apiSecret: '%env(APP_TWITTER_API_SECRET)%'
          accessToken: '%env(APP_TWITTER_ACCESS_TOKEN)%'
          accessTokenSecret: '%env(APP_TWITTER_ACCESS_TOKEN_SECRET)%'
